task: sopenbookqa_val
dataset_path: openbookqa
dataset_name: main
output_type: multiple_choice
training_split: validation
validation_split: train
test_split: train
doc_to_text: question_stem
doc_to_target: "{{choices.label.index(answerKey.lstrip())}}"
doc_to_choice: "{{choices.text}}"
process_docs: !function utils.process_docs
should_decontaminate: true
doc_to_decontamination_query: question_stem
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
