task: ssocial_iqa_val
dataset_path: social_i_qa
dataset_name: null
output_type: multiple_choice
training_split: validation
validation_split: train
doc_to_text: "Q: {{context}} {{question}}\nA:"
target_delimiter: " "
process_docs: !function utils.preprocess_docs
doc_to_choice: !function utils.doc_to_choice
doc_to_target: "{{ (label|int) - 1 }}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 0.0
